# Generated by Django 5.1.5 on 2025-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0003_remove_workerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
