# Generated by Django 5.1.5 on 2025-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0005_alter_workerprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
